[package]
name = "cube-renderer"
version = "0.1.0"
authors = ["Vinícius Souza <vinicius.rsouza07@gmail.com>"]
description = "It renders The Cube."
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"